version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

branches:
  only:
    - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
  
install:
  # Install repo specific stuff here
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v4.0.0/nuget.exe

before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/IdentityServer4.Contrib.LiteDB.sln --verbosity m

build_script:
    - cmd: dotnet build ../src/IdentityServer4.Contrib.LiteDB.sln -c Release
    - cmd: dotnet pack  -c Release /p:PackageVersion={version} 

 
  
artifacts:
- path: '**\*.nupkg'
  name: IdentityServer4.Contrib.LiteDB
 
deploy:
- provider: NuGet
    api_key:
    secure: a00q68cpfrfuba65uxtdd07m
  skip_symbols: true