version: 1.0.{build}
image: Visual Studio 2017

branches:
  only:
    - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
  
install:
  # Install repo specific stuff here
  
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/IdentityServer4.Contrib.LiteDB/IdentityServer4.Contrib.LiteDB.csproj --verbosity m
  - cmd: dotnet restore ./src/IdentityServer4.LiteDB.Tests/IdentityServer4.LiteDB.Tests.csproj --verbosity m
  - cmd: dotnet restore ./src/PagesWebApp/PagesWebApp.csproj --verbosity m
  
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

build:
  project: src/IdentityServer4.Contrib.LiteDB.sln

after_test:
  

artifacts:
 
    
 

#uncomment to publish to NuGet
#deploy:
#  provider: NuGet
#  api_key:
#    secure: n/2gZwCGLcoLBr5nGu5akS0IFQ1YHciI6Wz0NGC+1mLTUtO08Uy+TWn7OtyLG9v3
#  artifact: /.*\.nupkg/
